### ISSUE TITLE
[Tracking] A working release

### ISSUE THREAD

**Issue by elpiel** [AeroRust/nanosat-workshop#5]
- [ ] clean up all the logic from `skeleton-solutions` for the exercises and update the default `skeleton` branch
- [x] mdbook & Docs deployment to GH pages - can be found at https://aerorust.org/nanosat-workshop
- [x] test the solutions on the hardware
- [x] book - link to various docs for Application & exercises
- [ ] book - Explain the repo structure - `skeleton` for exercises and `skeleton-solutions` for the implemented exercises
- [ ] 3D frame cad files
